spring:
  application:
    name: app

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: false

  redis:
    host: localhost
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
  cache:
    type: redis
springdoc:
  swagger-ui:
    path: /swagger-ui/
    enabled: true
  api-docs:
    enabled: true

server:
  port: 8090



